platform :ios, '12.0'

def pods
    pod 'SwiftEventBus'
    pod 'ESTabBarController-swift'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftyAttributes'
    pod "Agrume"
    pod 'UITextView+Placeholder'
    pod 'SwifterSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Then'
    pod 'Reusable'
    pod 'ActionSheetPicker-3.0'
    pod 'SnapKit'
    pod 'Swinject'
    pod 'SwinjectAutoregistration'
    pod 'RxDataSources'
    pod 'KRProgressHUD'
    pod 'SwiftEventBus'
    pod 'Kingfisher'
end

target 'RobRoo' do
    use_frameworks!
    inhibit_all_warnings!
    pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
